services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: utterfresh_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  utterfresh_production_gathering_sys-app:
    container_name: utterfresh-container
    image: utterfresh_production_gathering_sys-app:latest
    depends_on:
      - postgres_db  # Make sure database starts first
    ports:
      - "8080:8080"

volumes:
  postgres_data:
