services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: utterfresh_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - utterfresh_network

  utter-pdgs-api:
    container_name: utter-pdgs-api
    build:
      context: ./
    image: utter-pdgs-api:dev-v1.2.7
    depends_on:
      - postgres_db
    ports:
      - "8083:8083"
    networks:
      - utterfresh_network

volumes:
  postgres_data:

networks:
  utterfresh_network:
    driver: bridge